# Describes a simple example flow that generates random numbers and then copies and links across 2 additional datasets

flow:
  source: input # uncomment to use the example generator
  # source: 'input/index' # uncomment to loop over an existing dataset
  stages: [example_stage0, example_stage1]
  drop: []

input:
  classname: ExampleGenerator
  dset_name: 'input/index'
  params:
    chunk_size: 1024

example_stage0:
  classname: ExampleStage
  params:
    output_dset: 'example_stage0/example'

example_stage1:
  classname: ExampleStage
  requires:
      - 'example_stage0/example' # load input/index -> example_stage0/example referred data
  params:
    output_dset: 'example_stage1/example'

