# Describes a simple test flow that copies one dataset to others

flow:
  source: input/events
  stages: [test_stage0, test_stage1]

# input:
#   classname: H5FlowDatasetLoopGenerator
#   dset_name: input/events
#   params:
#     chunk_size: 1024

test_stage0:
  classname: TestStage
  params:
    input_dset: 'input/events'
    output_dset: 'test_stage0/events'

test_stage1:
  classname: TestStage
  params:
    input_dset: 'input/events'
    output_dset: 'test_stage1/events'
    requires:
      - 'test_stage0/events'


