# Describes a simple test flow that copies one dataset to others

flow:
  source: input/events
  stages: [test_stage0, test_stage1]

test_stage0:
  classname: Test
  params:
    output_dset: events

test_stage1:
  classname: Test
  params:
    output_dset: events
    requires:
      - test_stage0/events
